# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Area')),
            ],
        ),
        migrations.CreateModel(
            name='MarkedVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Area')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='area',
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person'),
        ),
        migrations.AddField(
            model_name='markedvacancy',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person'),
        ),
        migrations.AddField(
            model_name='markedvacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Vacancy'),
        ),
        migrations.AddField(
            model_name='markedarea',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person'),
        ),
    ]
