# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170316_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_birth',
            field=models.DateField(null=True),
        ),
    ]
