# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170316_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
