# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170316_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
