# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_person_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='istate',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
