# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170317_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AreaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Area')),
            ],
        ),
        migrations.AddField(
            model_name='areaanswer',
            name='AreaQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AreaQuestion'),
        ),
    ]
