# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170317_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='attr',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
